---
driver:
  name: vagrant
  customize:
    memory: 13000
    natdnshostresolver1: "on"
    natdnsproxy1: "on"
    nictype1: "virtio"
    cpus: 1
  network:
  - ["forwarded_port", {guest: 3306, host: 50070}]
  - ["forwarded_port", {guest: 8080, host: 8080}]
  - ["forwarded_port", {guest: 8088, host: 8088}]
  - ["forwarded_port", {guest: 8181, host: 8181}]
  - ["forwarded_port", {guest: 9088, host: 9088}]
  - ["forwarded_port", {guest: 4848, host: 4848}]
  - ["forwarded_port", {guest: 50070, host: 51070}]
  - ["forwarded_port", {guest: 50075, host: 51075}]
  - ["forwarded_port", {guest: 9200, host: 9200}]
  - ["forwarded_port", {guest: 9009, host: 9999}]
  - ["forwarded_port", {guest: 22, host: 9191}]

provisioner:
  name: chef_solo
#  require_chef_omnibus: 12.4.3

platforms:

#  - name: ubuntu-15.04
#  - name: ubuntu-14.04
  - name: centos-7.0

suites:
  - name: default
    run_list:
       - recipe[kagent::install]
       - recipe[hopsworks::install]
       - recipe[ndb::install]
       - recipe[hops::install]
       - recipe[elastic::install]
       - recipe[zeppelin::install]
       - recipe[hadoop_spark::install]
       - recipe[flink::install]
#       - recipe[adam::install]
#       - recipe[kzookeeper::install]
#       - recipe[kkafka::install]
       - recipe[ndb::mgmd]
       - recipe[ndb::ndbd]
       - recipe[ndb::mysqld]
       - recipe[hops::ndb]
       - recipe[hops::nn]
       - recipe[hops::dn]
       - recipe[hops::rm]
       - recipe[hops::nm]
       - recipe[hops::jhs]
       - recipe[elastic::default]
       - recipe[hadoop_spark::yarn]
       - recipe[flink::yarn]
       - recipe[hopsworks]
       - recipe[hopsworks::dev]
#       - recipe[adam]

    attributes:
#         download_url: "http://192.168.1.2/hops"
        # authorization:
        #    sudo:
        #      users: ['vagrant']
        #      passwordless: true
        #      include_sudoers_d: true
         kzookeeper:
            default:
               private_ips: ["10.0.2.15"]
         kkafka:
            ulimit_file: 128000
            default:
                private_ips: ["10.0.2.15"]
         kagent:
            private_ips: ["10.0.2.15"]
            enabled: true
         elastic:
            default:
                private_ips: ["10.0.2.15"]
                public_ips: ["10.0.2.15"]
            private_ips: ["10.0.2.15"]
            public_ips: ["10.0.2.15"]
            checksum: "069cf3ab88a36d01f86e54b46169891b0adef6eda126ea35e540249d904022e1"
            version: 2.1.2
            jdbc_importer:
                version: 2.1.1.2
         ndb:
            mgmd:
               private_ips: ["10.0.2.15"]
            ndbd:
               private_ips: ["10.0.2.15"]
            mysqld:
               private_ips: ["10.0.2.15"]
            memcached:
               private_ips: ["10.0.2.15"]
            private_ips: ["10.0.2.15"]
            public_ips: ["10.0.2.15"]
            enabled: "true"
         hops:
            nn:
               private_ips: ["10.0.2.15"]
            dn:
               private_ips: ["10.0.2.15"]
            rm:
               private_ips: ["10.0.2.15"]
            nm:
               private_ips: ["10.0.2.15"]
            jhs:
               private_ips: ["10.0.2.15"]
            yarn:
               rm_distributed: "false"
            use_hopsworks: "true"
         apache_hadoop:
            hdfs:
               user: glassfish
            yarn: 
               user: glassfish
               nm:
                   memory_mbs: '2656'
               vcores: '2'
            mr: 
               user: glassfish
            nn:
               private_ips: ["10.0.2.15"]
            dn:
               private_ips: ["10.0.2.15"]
            rm:
               private_ips: ["10.0.2.15"]
            nm:
               private_ips: ["10.0.2.15"]
            jhs:
               private_ips: ["10.0.2.15"]
         zeppelin:
            default:
               private_ips: ["10.0.2.15"]
            private_ips: ["10.0.2.15"]
            public_ips: ["10.0.2.15"]
         hadoop_spark:
            user: glassfish
            worker:
               private_ips: ["10.0.2.15"]
            master:
               private_ips: ["10.0.2.15"]
            historyserver:
               private_ips: ["10.0.2.15"]
            private_ips: ["10.0.2.15"]
         flink:
            user: glassfish
            jobmanager:
               private_ips: ["10.0.2.15"]
            taskmanager:
               private_ips: ["10.0.2.15"]
         hopsworks:
            #port: 80
            default:
               private_ips: ["10.0.2.15"]
            private_ips: ["10.0.2.15"]
            public_ips: ["10.0.2.15"]
            user_envs: "false"
            war_url: "http://snurran.sics.se/hops/hopsworks.war"
#            twofactor_auth: true
         glassfish:
            user: glassfish
         private_ips: ["10.0.2.15"]
         public_ips: ["10.0.2.15"]
         vagrant: "true"
         # glassfish:
         #      version: "4.1"
         #      package_url: "http://193.10.67.171/hops/glassfish-4.1.zip"
         #      domains: 
         #        domain1: 
         #          config: 
         #            port: 7070
         #            admin_port: 4848
         #            username: admin
         #            password: admin
         #            master_password: mykeystorepassword
         #            remote_access: true
         # java:
         #     install_flavor: oracle
         #     jdk_version: 7
         #     oracle:       
         #       accept_oracle_download_terms: "true"

