Encoding.default_external = "UTF-8"
source 'https://supermarket.chef.io'

metadata

cookbook 'conda', github: "logicalclocks/conda-chef", branch: "3.0"
cookbook 'kagent', github: "logicalclocks/kagent-chef", branch: "3.0"
cookbook 'hops', github: "logicalclocks/hops-hadoop-chef", branch: "3.0"
cookbook 'ndb', github: "logicalclocks/ndb-chef", branch: "3.0"
cookbook 'hadoop_spark', github: "logicalclocks/spark-chef", branch: "3.0"
cookbook 'flink', github: "logicalclocks/flink-chef", branch: "3.0"
cookbook 'livy', github: "logicalclocks/livy-chef", branch: "3.0"
cookbook 'epipe', github: "logicalclocks/epipe-chef", branch: "3.0"
cookbook 'tensorflow', github: "logicalclocks/tensorflow-chef", branch: "3.0"
cookbook 'dela', github: "logicalclocks/dela-chef", branch: "3.0"
cookbook 'kzookeeper', github: "logicalclocks/kzookeeper", branch: "3.0"
cookbook 'kkafka', github: "logicalclocks/kafka-cookbook", branch: "3.0"
cookbook 'elastic', github: "logicalclocks/elasticsearch-chef", branch: "3.0"
cookbook 'hopslog', github: "logicalclocks/hopslog-chef", branch: "3.0"
cookbook 'hopsmonitor', github: "logicalclocks/hopsmonitor-chef", branch: "3.0"
cookbook 'hops_airflow', github: "logicalclocks/airflow-chef", branch: "3.0"
cookbook 'hive2', github: "logicalclocks/hive-chef", branch: "3.0"
cookbook 'consul', github: "logicalclocks/consul-chef", branch: "3.0"
cookbook 'kube-hops', github: "logicalclocks/kube-hops-chef", branch: "3.0"
cookbook 'cloud', github: "logicalclocks/cloud-chef", branch: "3.0"
cookbook 'onlinefs', github: "logicalclocks/onlinefs-chef", branch: "3.0"

cookbook 'ulimit', github: "logicalclocks/chef-ulimit", branch: "3.0"
cookbook 'glassfish', github: "logicalclocks/chef-glassfish", branch: "3.0"
cookbook 'java', github: "logicalclocks/java", branch: "v7.0.0-1"
